# Generated by Django 4.2.30 on 2026-05-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_studymaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('evaluated', 'Evaluated'), ('late', 'Late')], default='pending', max_length=20),
        ),
    ]
