# Generated by Django 4.2.30 on 2026-05-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lecture',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
