# Generated by Django 4.2.30 on 2026-05-15 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_department_alter_user_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='code',
        ),
    ]
